
services:
  zookeeper:

  broker:

  schema-registry:

  connect:

  # ksql-server:

  # ksql-cli:

  # ksql-datagen:

  rest-proxy:

  cli:

  elasticsearch:

  kibana:

  topics-ui:

  connect-ui:  
  
  datagen:

volumes:
    mi2: {}
